### ISSUE TITLE
HTTP Method 구현

### ISSUE THREAD

**Issue by Devdha** [webserv-80000coding-jiphyeonjeon/webserv#21]
- [x] config 파일 확인하여 path 구성
- [x] 파일 확인하는 방식 확인 및 구현
- [x] GET
- [x] POST
- [x] DELETE
- [x] Process 함수 내 exception 처리 로직
- [x] PUT 메소드 구현
- [x] HEAD 메소드 헤더 입력 로직
- [x] 각 메소드 경로 체크 함수 추가
- [x] CGI 분기문 구현
- [x] #39
- [x] GET - 파일에 권한 확인 여부 결정 및 구현
- [ ] GET - autoindex

**Comment by Hyoj-Kim** [comment]
GET 체크리스트
1. 파일
    - 해당 위치에 존재하는지만 판단 - (200 / 404)
2. 폴더
    - autoindex: on -> 바로 autoindex page 보내주기 (200)
    - autoindex: off 
        - getIndex()로 가져온 vector들에 해당하는 파일 확인하기 (200 / 404)
