### ISSUE TITLE
HTTP Request 파싱 중 발생한 exception 처리

### ISSUE THREAD

**Issue by Devdha** [webserv-80000coding-jiphyeonjeon/webserv#28]
### 현재 구현
Request 파싱 중 예외 사항이 발생하는 경우, 의도한 동작은 예외 사항에 맞는 status code를 설정하여 응답해야 하지만,
현재는 에러 리턴을 받아서 클라이언트를 끊어버림

### 해결 방법
- [x] Webserv 클래스에서 kRecvSuccess와 구분할 수 있는 플래그 추가
- [x] Processor 클래스에서 exception catch 하는 경우, build()
- [x] Process 함수에서 Request 파싱 에러일 경우, 메소드 함수 호출 안하도록 설정

**Comment by Hyoj-Kim** [comment]
![Image](https://user-images.githubusercontent.com/76509884/183074079-5e812117-997d-4ef0-97ef-a1f39b59ced2.png)



![Image](https://user-images.githubusercontent.com/76509884/183074237-180a840c-30e8-4217-a609-6ed3a725f9e4.png)
